name: "Verify React build"
on: workflow_call

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Lint (If exists)
        run: npm run lint --if-present
      - name: TSC (If exists)
        run: npm run tsc --if-present -- --noEmit
      - name: Test (If exists)
        run: npm run test --if-present
      - name: Build (If exists)
        run: npm run build --if-present
      - name: Build Storybook (If exists)
        run: npm run build:storybook --if-present
